plank:
  default_decoration_config:
    timeout: 7200000000000 # 2h
    grace_period: 15000000000 # 15s
    utility_images:
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20181119-ffa9de5"
      initupload: "gcr.io/k8s-prow/initupload:v20181119-ffa9de5"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20181119-ffa9de5"
      sidecar: "gcr.io/k8s-prow/sidecar:v20181119-ffa9de5"
    gcs_configuration:
      bucket: "kubernetes-jenkins"
      path_strategy: "legacy"
      default_org: "kubernetes"
      default_repo: "kubernetes"
    gcs_credentials_secret: "service-account"

presubmits:
  paulbhart/prow-test:
  - name: unit-tests
    always_run: true
    skip_report: false
    context: unit-tests
    agent: kubernetes
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]         
    trigger: "(?m)^/test this"
    rerun_command: "/test this"
