periodics:
- interval: 10m
  name: echo-test
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
postsubmits:
  paulbhart/prow-test:
  - name: test-postsubmit
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
presubmits:
  paulbhart/prow-test:
  - name: test-presubmit
    always_run: true
    skip_report: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
